version: '2'
services:
    bpodirectorymanager-app:
        image: bpodirectorymanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bpodirectorymanager-mysql:3306/bpodirectorymanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8083:8083
    bpodirectorymanager-mysql:
        extends:
            file: mysql.yml
            service: bpodirectorymanager-mysql
